version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-8081}:8081"
    environment:
      SESSION_SECRET: "${SESSION_SECRET:-your-super-secret-key}"
      SMTP_HOST: "${SMTP_HOST:-mailhog}"
      SMTP_PORT: "${SMTP_PORT:-1025}"
      DB_HOST: "${DB_HOST:-db}"
      DB_PORT: "${DB_PORT:-5432}"
      DB_USER: "${DB_USER:-user}"
      DB_PASSWORD: "${DB_PASSWORD:-password}"
      DB_NAME: "${DB_NAME:-seriestracker}"
      DB_SSLMODE: "${DB_SSLMODE:-disable}"
      OMDB_API_KEY: "${OMDB_API_KEY:-fbd55d5e}"
    depends_on:
      db:
        condition: service_healthy
      mailhog:
        condition: service_started
    networks:
      - series_tracker_network

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: "${DB_NAME:-seriestracker}"
      POSTGRES_USER: "${DB_USER:-user}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-password}"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - series_tracker_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: "none"
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - series_tracker_network

volumes:
  pg_data:


networks:
  series_tracker_network:
    driver: bridge
